spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/meal_planner_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

server:
  port: 8081
  servlet:
    context-path: /api

# JWT (dùng secret đơn giản khi test local)
app:
  jwt:
    secret: KjQwt1HL5uMkcx8KSfPWMJ3CrKpqbdPk2ymjGwV4yeJ1xNRy54yJwCrUOTMJqnEvfIMlkG9DQUkMlUVvNzG6DzKQ1/gTxO/ZKdi7bhA7g++mu4Xw5/GQwDXP/NxF5ei5oI7LjIAGN2HkhXf7QPeJGoicCoieczfQZXALkx9W+91NRYcNeyqlCN9dahvBHyB28IAT9sm1EoqQ2o/ROjl6Qn9YQq5y6GsknuOQzduNuizulOduUdSQJ04e20i8Cf7u843/Q1jVYfGtiDSWmdYoRoxGRnLOajELhqE+ruRGvFKL+tsCJ8NibsbZuuf49qfomCyfEm3lLBHCUh60RqB51A==
    expiration-ms: 86400000        # 1 ngày
    refresh-expiration-ms: 604800000  # 7 ngày

#   # CORS: cho phép frontend dev chạy trên cổng khác
#   cors:
#     allowed-origins:
#       - http://localhost:3000
#       - http://localhost:5173
#     allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
#     allowed-headers: "*"
#     allow-credentials: true